### ISSUE TITLE
使用redis的时候偶然出现无法链接的情况

### ISSUE THREAD

**Issue by zxz524** [Coldairarrow/Colder.Admin.AntdVue#167]
`System.Exception: 【127.0.0.1:6379/5】状态不可用，等待后台检查程序恢复方可使用。Connection was not opened
 ---> CSRedis.RedisClientException: Connection was not opened
   at CSRedis.Internal.IO.RedisIO.GetOrThrow[T](T obj)
   at CSRedis.Internal.IO.RedisIO.get_Stream()
   at CSRedis.Internal.IO.RedisIO.Write(Byte[] data)
   at CSRedis.Internal.RedisConnector.Call[T](RedisCommand`1 command)
   at CSRedis.RedisClient.Write[T](RedisCommand`1 command)
   at CSRedis.RedisClient.Ping()
   at CSRedis.RedisClientPool.Return(Object`1 obj, Exception exception, Boolean isRecreate)
   --- End of inner exception stack trace ---
   at CSRedis.Internal.ObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   at CSRedis.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.HMGet[T](String key, String[] fields)
   at Microsoft.Extensions.Caching.Redis.CSRedisCache.GetAndRefresh(String key, Boolean getData)
   at Microsoft.Extensions.Caching.Redis.CSRedisCache.Get(String key)
   at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.GetString(IDistributedCache cache, String key)
   at Jason.ApiAdmin.CheckSignAttribute.OnActionExecuting(ActionExecutingContext filterContext) in D:\Visual Studio 2019\Projects\HuNiuKuaiKe\src\Jason.ApiAdmin\Filters\对外接口签名校验\CheckSignAttribute.cs:line 148`

**Comment by remixjc** [comment]
你这个一般是Redis的问题

**Comment by zxz524** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，你的邮件已经收到，我会尽快给您回复。
